name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.12"]

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        run: pip install poetry==1.8.4

      - name: Install dependencies
        run: poetry install

      - name: Start LocalStack with Docker Compose
        run: docker compose up -d

      - name: Run pylint
        run: poetry run pylint --fail-under 4 app

      - name: Run Unit Tests
        run: poetry run pytest tests/test_case.py -v

      - name: Run BDD Tests
        run: poetry run behave features/

      - name: Run Integration Tests with Coverage
        run: |
          poetry run pytest --maxfail=1 --disable-warnings -v tests/test_integration.py
          poetry run coverage run -m pytest tests/test_integration.py
          poetry run coverage report -m

      - name: Teardown Docker
        if: always()
        run: docker compose down